[build]
  base = "/"
  command = "npm run build"
  publish = "dist"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://whldjwyzmvjgfsqlbqhk.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobGRqd3l6bXZqZ2ZzcWxicWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMzM3MDYsImV4cCI6MjA1NDkwOTcwNn0.8QP00tyT5yGSwzaPgVrE1hkTwFvLPV1JkI18qihzumw"
  VITE_ENABLE_LIVE_CHAT = "true"
  VITE_ENABLE_AR_NAVIGATION = "true"
  VITE_ENABLE_CRYPTO_PAYMENTS = "true"
  VITE_ADMIN_EMAIL = "phunguss10@gmail.com"

# Force HTTPS and security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob:; font-src 'self' https: data:; connect-src 'self' https: wss:;"